// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/21hack02win/nascalay-backend/interfaces/handler"
	"github.com/21hack02win/nascalay-backend/interfaces/repository"
	"github.com/21hack02win/nascalay-backend/usecases/service"
)

// Injectors from wire.go:

func injectServer() handler.ServerInterface {
	serviceService := service.NewService()
	repositoryRepository := repository.NewRepository()
	serverInterface := handler.NewHandler(serviceService, repositoryRepository)
	return serverInterface
}
