// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/21hack02win/nascalay-backend/interfaces/handler"
	"github.com/21hack02win/nascalay-backend/interfaces/repository"
	"github.com/21hack02win/nascalay-backend/oapi"
	"github.com/21hack02win/nascalay-backend/usecases/service"
	"github.com/21hack02win/nascalay-backend/usecases/service/ws"
)

// Injectors from wire.go:

func injectServer() oapi.ServerInterface {
	serviceService := service.NewService()
	repositoryRepository := repository.NewRepository()
	hub := ws.NewHub(repositoryRepository)
	streamer := ws.NewStreamer(hub)
	serverInterface := handler.NewHandler(serviceService, repositoryRepository, streamer)
	return serverInterface
}
